apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-backend-app
  template:
    metadata:
      labels:
        app: cloudmart-backend-app
    spec:
      serviceAccountName: cloudmart-pod-execution-role
      containers:
        - name: cloudmart-backend-app
          image: public.ecr.aws/l4c0j8h9/cloudmart-backend:latest
          env:
            - name: PORT
              value: "5000"
            - name: AWS_REGION
              value: "us-east-1"
            - name: BEDROCK_AGENT_ID
              value: "xxxxxx"
            - name: BEDROCK_AGENT_ALIAS_ID
              value: "xxxx"
            - name: OPENAI_API_KEY
              value: "xxxxxx"
            - name: OPENAI_ASSISTANT_ID
              value: "xxxx"
